// PRIMARY LIST OF ALL THE CODE WHICH WILL BE WRITTEN IN AN OUR BUDGET APP ///


// BEFORE CODING OR STARTING A PROJECT WE MUST FIRST WRITE OUT A LIST OF PROGRAMS OR A BLUE PRINT OF WHAT THE APP WOULD LOOK LIKE //







// HOW TO USE MODULE PATTERNS //


// WHY WE MAKE USE OF MODULES //

///* MODULES ARE PRIMARILY USED TO KEEP PIECES OF CODE THAT ARE RELATED TO ONE ANOTHER TOGETHER 
///*


// DATA INCAPSULATION ALLOWS US TO HIDE THE IMPLEMENTATION DETAILS OF A SPECIFIC MODULE FROM OF A MODULE FROM THE OUTSIDE SCOPE SO THAT WE ONLY EXPOSE A PUBLIC INTERFACE CALLED THE API(APPLICATION PROGRAMMING INTERFERFACE //

